### ISSUE TITLE
Feature Request: Use file last modified timestamp if there is no git info

### ISSUE THREAD

**Issue by Ptyool** [timvink/mkdocs-git-revision-date-localized-plugin#146]
Hi,
Would it be possible to change the behavior, from using the current time if there is no git info, to using the file last modified timestamp :
https://github.com/timvink/mkdocs-git-revision-date-localized-plugin/blob/3f39e6558213de330b4fbb5e6473aaf95a07713c/src/mkdocs_git_revision_date_localized_plugin/util.py#L142
Thank you.

**Comment by timvink** [comment]
That works on your local machine, but if you use a build system it's meaningless (because the repo is cloned somewhere else). That will mean inconsistent behaviour & a lot of confusion (=bug reports)

**Comment by Ptyool** [comment]
Hi,
I understand why you don't want to change the default behavior, however it could be an option of the plugin.
Our use case is to add doc from other repo, so there is no git log for those files, but we are able to retrieve the last modification time and set the correct mtime on those files before "mkdoc build".
Thank you.

**Comment by timvink** [comment]
If I add an option, I will still have to maintain it, _and_ make sure the different combinations of settings make sense. I prefer this plugin to do 1 thing well.

Some alternatives you can consider/research:

- the `projects` plugin allows you to build multiple projects together: https://squidfunk.github.io/mkdocs-material/plugins/projects/?h=projects 
- You might be able keep the git info from the other repo by using git submodules when adding it
- You can add a [mkdocs hook](https://www.mkdocs.org/user-guide/configuration/#hooks) (basically a mini plugin) to add to a page information the file date. Then you can make a custom template where you use the file date if available, and otherwise fallback to the git date. See https://timvink.github.io/mkdocs-git-revision-date-localized-plugin/howto/override-a-theme/ on overriding themes. 
- mkdocs-macros plugin also offer git information and a range of other things on a page. You might be able to convince the author of that plugin to also add the file last modified and file created date. https://github.com/fralau/mkdocs-macros-plugin

**Comment by timvink** [comment]
Closing as won't implement
