### ISSUE TITLE
Feature Request: build date by default not as "fallback"

### ISSUE THREAD

**Issue by buhtz** [timvink/mkdocs-git-revision-date-localized-plugin#150]
Hello,
I was searching existing issues but couldn't find something like this.

It would be nice if your plugin is able to use the build date (mkdocs build) as the primary option and not only as a fallback. The fallback works only if it is not a git repo. But in my case there is a git repo. I don't care about the git log or the md-files last mod date.

Do you see a way to archiev or implement it?

Related
https://github.com/squidfunk/mkdocs-material/discussions/7627

**Comment by timvink** [comment]
I think that deserves it's own plugin. Feel free to fork this one and remove all the git stuff!

The reason is maintainability, and simplicity. Too many options and there are too many combinations to consider.

Also related: https://github.com/timvink/mkdocs-git-revision-date-localized-plugin/issues/146

Closing as won't fix

**Comment by timvink** [comment]
I agree, git should be part of mkdocs. Just trying to be helpful with this plugin.

"wontfix" is one of the default tags in GitHub. Which I used as 'won't implement this feature'. Perhaps not the right tag. Definitely not intended as unpolite.
