### ISSUE TITLE
Add most recent update date to main page

### ISSUE THREAD

**Issue by awesomeindustries** [timvink/mkdocs-git-revision-date-localized-plugin#19]
I find it usefull to see a 'updated by' date at the bottom of each page. However, I'm looking for a way to add an overall 'last updated' date to the main page, for example to the header.

Do you have a suggestion how to do that?

**Comment by timvink** [comment]
Do you mean the last update to the site (any page)?

That would be a great addition. I'm working on a large release for [mkdocs-git-authors-plugin ](https://github.com/timvink/mkdocs-git-authors-plugin). In that plugin I already process all pages with git, and adding the git revision date should be fairly easy. I plan to merge both plugins due to the similarities in the future.

Planning to add two tags: 
- `{{ git_site_last_update }}` (last update of any page in site)
- `{{ git_page_last_update }}` (last update of page)

I will report in this issue once the functionality is there.

**Comment by awesomeindustries** [comment]
Yes that's exactly the feature I'm suggesting!

For now I got it to work with this:

`        # Date of the page
        file_revision_dates = self.util.get_revision_date_for_file(
            path=page.file.abs_src_path,
            locale = self.locale
        )
        file_revision_date = file_revision_dates[self.config['type']]
        page.meta['git_revision_date_localized'] = file_revision_date

        # Date of the full documentation
        main_revision_dates = self.util.get_revision_date_for_file(
            path=os.path.dirname(page.file.abs_src_path),
            locale=self.locale
        )
        main_revision_date = main_revision_dates[self.config['type']]
        page.meta['git_main_date_localized'] = main_revision_date

        temp_str = re.sub(r"\{\{\s*[page\.meta\.]*git_revision_date_localized\s*\}\}",
                          file_revision_date,
                          markdown,
                          flags=re.IGNORECASE)

        return re.sub(r"\{\{\s*[page\.meta\.]*git_main_date_localized\s*\}\}",
                      main_revision_date,
                      temp_str,
                      flags=re.IGNORECASE)`
