### ISSUE TITLE
[pr discuss] Add {{git_creation_date_localized}}

### ISSUE THREAD

**Issue by PegasisForever** [timvink/mkdocs-git-revision-date-localized-plugin#49]
Hi!

I added the ability for this plugin to add creation dates to pages. (Because I need it for my personal blog) ([repo](https://github.com/PegasisForever/mkdocs-git-revision-date-localized-plugin))

Since `CONTRIBUTING.md` wrote "...That means not extending the functionality of this plugin", I'm wondering whether my pr of adding this functionality will be accepted?

If it won't, I won't bother writing tests for it :)

**Comment by timvink** [comment]
Hi @PegasisForever !

Thanks for this :) I had a look at the changes you made [link](https://github.com/timvink/mkdocs-git-revision-date-localized-plugin/compare/master...PegasisForever:master) and looks nice!

I'm open to adding a `git_creation_date_localized`. It's relatively cheap, because it just means a bit more parsing of the `git log` output we already have. Some thoughts:

- I wonder what the performance overhead is of getting the full logs instead of just the top one for large projects ([see here](https://github.com/timvink/mkdocs-git-revision-date-localized-plugin/compare/master...PegasisForever:master#diff-00b1f736d69bb089d8eafceeb52bc04b19ebecf339a8b33ccc3404a21ebd32cbL108-R106)). Probably better to only get the full logs when you need it (so when `enable_creation_date` is True), otherwise keep `n=1`. 
- `mkdocs-material` offers native support for `git-revision-date-localized` including all required translations (see f.e. [here](https://github.com/squidfunk/mkdocs-material/blob/master/src/partials/languages/en.html#L52) or [here](https://github.com/squidfunk/mkdocs-material/blob/master/src/partials/source-date.html)). We'll have to align with the author, update the `source_date` partial and language templates. Would you be willing to pick that up also?

We can align on implementation specifics if you open a PR. I have been planning to create a documentation website for this plugin, I will pick that up so we can document this feature there.

**Comment by PegasisForever** [comment]
**Performance:**

I found out git log has an reverse option so we can just get the first log in the reverse order.

**Theme integration:**

Yes, I'll deal with that.

I'll open a pr later today (or tomorrow).
