### ISSUE TITLE
Option to set a own date format separate from the locale

### ISSUE THREAD

**Issue by Andre601** [timvink/mkdocs-git-revision-date-localized-plugin#82]
It is surprising that there isn't a setting to set your own date format to use.

The only current way is to use the `locale` option which has unwanted side effects such as altering the displayed name of the month.

The reason why there should be such an option is the simple fact, that not everyone is actually using the same format for a date commonly used in that language.

As an example am I using English as my site's primary language, while using the german date format (`01. January 2022`) over the English one (`January 01, 2022`).
This causes an issue where the plugin is using the English format while I would like to use the german one instead. The issue here is that changing the locale to `de` would change `January` to `Januar` which is in conflict with my site's main language.

I would really appreciate it if such a setting could be added.

**Comment by timvink** [comment]
> It is surprising that there isn't a setting to set your own date format to use.

I guess it is. Maybe it's what happens when a plugin organically grows a bit.. I might have designed it different if I would have to write it from scratch now.

So let's design it :)

The format can be the format for `strftime` ([cheatsheet](https://strftime.org/)), so you can use a format like `%d. %B %Y` (for `01. January 2022`).

The format would apply to `type: date`, `type: datetime`, `type: iso_date`, `type: iso_datetime`, basically everything except `timeago`.

We could add a another type, name it `custom`, and add an extra option called `custom_format`. It can default to something simple like `%Y-%m-%d` (the only true date format, see [https://xkcd.com/1179/](https://xkcd.com/1179/) ;))

That way, we can also make the `custom` type available as [extra variables available for overriding themes](https://timvink.github.io/mkdocs-git-revision-date-localized-plugin/available-variables/).

I am also planning on adding support for overriding settings on a per-page basis, using YAML frontmatter, to support use-cases like #73. You should then be able to override `custom_format` to change the format for a given page.

Thoughts?

**Comment by Andre601** [comment]
That sounds good.

I would be fine with a `custom` type with an extra setting... Tho, maybe to save effort, how about just have that separate option and if it is present, just override the type as a whole?

**Comment by timvink** [comment]
Because then you can do this:

```yaml
plugins:
  - git-revision-date-localized:
      type: timeago
      custom_format: "%Y"
```

And on a specific, individual page, choose to change the type:

```markdown
---
git-revision-date-localized--type: custom
---

# My page
```

I'll pick this up next time I find a chunk of time to work on the plugin :)

**Comment by Andre601** [comment]
> Because then you can do this:
> 
> ```yaml
> plugins:
>   - git-revision-date-localized:
>       type: timeago
>       custom_format: "%Y"
> ```
> 
> And on a specific, individual page, choose to change the type:
> 
> ```gfm
> ---
> git-revision-date-localized--type: custom
> ---
> 
> # My page
> ```
> 
> I'll pick this up next time I find a chunk of time to work on the plugin :)

Well... In that case could you just provide the custom date directly to the front matter for the same effect I would say.

**Comment by Andre601** [comment]
I'm not sure if that actually works?

I have this PR from Dependabot open that updates the plugin:
https://github.com/Andre601/blog/pull/45

And I also updated the configuration within that branch itself:
https://github.com/Andre601/blog/blob/dependabot/pip/mkdocs-git-revision-date-localized-plugin-1.0.0/mkdocs.yml#L172-L174
https://github.com/Andre601/blog/blob/dependabot/pip/mkdocs-git-revision-date-localized-plugin-1.0.0/mkdocs.yml#L224
https://github.com/Andre601/blog/blob/dependabot/pip/mkdocs-git-revision-date-localized-plugin-1.0.0/mkdocs.yml#L227

Yet, when I check the preview of the PR, is the date not updated and still shows in the format `%B %d, %Y`

Example page (Date at the bottom): https://www.andre601.ch/blog/posts/2020/12-20-in-defense-of-spigotmc/

I also cleared the cache on netlify to make sure it's not an issue caused by that...

**Comment by timvink** [comment]
Cool setup! Looks really good.

I cloned your repo, checked out the branch and previewed it locally:

![image](https://user-images.githubusercontent.com/5570380/155086342-9ca9dc3b-d8e4-4c60-a562-54741df71a57.png)

That's the `custom_format: '%d. %B %Y'` configured in your `mkdocs.yml`. Changing it also changes the format correctly.

So I'm not sure what's going on tbh. I don't have any experience with netlify. I would guess indeed some kind of caching going on..

**Comment by timvink** [comment]
Did you manage to fix it? Does it work for you locally as well?

**Comment by Andre601** [comment]
Was indeed a caching issue.
